mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090

dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
  nameserver:
    - https://dns.google/dns-query
  fallback:
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

proxies:
  - name: "root-proxy"
    type: http
    server: 31.59.20.176
    port: 6754
  - name: "intercept-proxy"
    type: http
    server: 23.95.150.145
    port: 6114

proxy-groups:
  - name: "rootgroup"
    type: select
    proxies:
      - "root-proxy"
  - name: "interceptgroup"
    type: select
    proxies:
      - "intercept-proxy"

rules:
  # Specific rule for ifconfig.me
  - DOMAIN,ifconfig.me,interceptgroup
  - DOMAIN,api.ipify.org,interceptgroup
  - DOMAIN-SUFFIX,googlevideo.com,interceptgroup
  
  # The "catch-all" rule set to DIRECT instead of a proxy
  - MATCH,rootgroup
